### ISSUE TITLE
Won't start if not in gemfile instead of gem install

### ISSUE THREAD

**Issue by GuillaumeLegendre** [Codaisseur/terminal-notifier-guard#33]
I don't want to modify the gemfile to install this gem. I want to use:
> $ gem install terminal-notifier-guard

But currently, each time I try to launch Guard he throw me this error:

> guard
> /Users/guillaumelegendre/.rvm/gems/ruby-2.3.0@investissement_pierre/gems/notiffany-0.0.8/lib/notiffany/notifier/base.rb:123:in `rescue in _require_gem': Please add "gem 'terminal-notifier-guard'" to your Gemfile and run your app with "bundle exec". (Notiffany::Notifier::Base::RequireFailed)
> 	from /Users/guillaumelegendre/.rvm/gems/ruby-2.3.0@investissement_pierre/gems/notiffany-0.0.8/lib/notiffany/notifier/base.rb:121:in `_require_gem'
> 	from /Users/guillaumelegendre/.rvm/gems/ruby-2.3.0@investissement_pierre/gems/notiffany-0.0.8/lib/notiffany/notifier/base.rb:58:in `initialize'
> 	from /Users/guillaumelegendre/.rvm/gems/ruby-2.3.0@investissement_pierre/gems/notiffany-0.0.8/lib/notiffany/notifier/detected.rb:92:in `new'
> 	from /Users/guillaumelegendre/.rvm/gems/ruby-2.3.0@investissement_pierre/gems/notiffany-0.0.8/lib/notiffany/notifier/detected.rb:92:in `add'
> 	from /Users/guillaumelegendre/.rvm/gems/ruby-2.3.0@investissement_pierre/gems/notiffany-0.0.8/lib/notiffany/notifier.rb:102:in `block in initialize'
> 	from /Users/guillaumelegendre/.rvm/gems/ruby-2.3.0@investissement_pierre/gems/notiffany-0.0.8/lib/notiffany/notifier.rb:101:in `each'
> 	from /Users/guillaumelegendre/.rvm/gems/ruby-2.3.0@investissement_pierre/gems/notiffany-0.0.8/lib/notiffany/notifier.rb:101:in `initialize'
> 	from /Users/guillaumelegendre/.rvm/gems/ruby-2.3.0@investissement_pierre/gems/notiffany-0.0.8/lib/notiffany/notifier.rb:42:in `new'
> 	from /Users/guillaumelegendre/.rvm/gems/ruby-2.3.0@investissement_pierre/gems/notiffany-0.0.8/lib/notiffany/notifier.rb:42:in `connect'
> 	from /Users/guillaumelegendre/.rvm/gems/ruby-2.3.0@investissement_pierre/gems/guard-2.13.0/lib/guard/notifier.rb:11:in `connect'
> 	from /Users/guillaumelegendre/.rvm/gems/ruby-2.3.0@investissement_pierre/gems/guard-2.13.0/lib/guard.rb:61:in `setup'
> 	from /Users/guillaumelegendre/.rvm/gems/ruby-2.3.0@investissement_pierre/gems/guard-2.13.0/lib/guard/commander.rb:32:in `start'
> 	from /Users/guillaumelegendre/.rvm/gems/ruby-2.3.0@investissement_pierre/gems/guard-2.13.0/lib/guard/cli/environments/valid.rb:16:in `start_guard'
> 	from /Users/guillaumelegendre/.rvm/gems/ruby-2.3.0@investissement_pierre/gems/guard-2.13.0/lib/guard/cli.rb:122:in `start'
> 	from /Users/guillaumelegendre/.rvm/gems/ruby-2.3.0@investissement_pierre/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
> 	from /Users/guillaumelegendre/.rvm/gems/ruby-2.3.0@investissement_pierre/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
> 	from /Users/guillaumelegendre/.rvm/gems/ruby-2.3.0@investissement_pierre/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
> 	from /Users/guillaumelegendre/.rvm/gems/ruby-2.3.0@investissement_pierre/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
> 	from /Users/guillaumelegendre/.rvm/gems/ruby-2.3.0@investissement_pierre/gems/guard-2.13.0/lib/guard/aruba_adapter.rb:32:in `execute'
> 	from /Users/guillaumelegendre/.rvm/gems/ruby-2.3.0@investissement_pierre/gems/guard-2.13.0/lib/guard/aruba_adapter.rb:19:in `execute!'
> 	from /Users/guillaumelegendre/.rvm/gems/ruby-2.3.0@investissement_pierre/gems/guard-2.13.0/bin/_guard-core:11:in `<main>'
> /Users/guillaumelegendre/.rvm/gems/ruby-2.3.0@investissement_pierre/gems/listen-3.0.6/lib/listen/fsm.rb:76:in `validate_and_sanitize_new_state': Listen::Listener can't change state from 'initializing' to 'stopped', only to: backend_started (ArgumentError)
> 	from /Users/guillaumelegendre/.rvm/gems/ruby-2.3.0@investissement_pierre/gems/listen-3.0.6/lib/listen/fsm.rb:55:in `transition'
> 	from /Users/guillaumelegendre/.rvm/gems/ruby-2.3.0@investissement_pierre/gems/listen-3.0.6/lib/listen/listener.rb:98:in `stop'
> 	from /Users/guillaumelegendre/.rvm/gems/ruby-2.3.0@investissement_pierre/gems/guard-2.13.0/lib/guard/aruba_adapter.rb:48:in `execute'
> 	from /Users/guillaumelegendre/.rvm/gems/ruby-2.3.0@investissement_pierre/gems/guard-2.13.0/lib/guard/aruba_adapter.rb:19:in `execute!'
> 	from /Users/guillaumelegendre/.rvm/gems/ruby-2.3.0@investissement_pierre/gems/guard-2.13.0/bin/_guard-core:11:in `<main>'
> 

If I add the line to the Gemfile everything work fine.

Do you have an idea why?

**Comment by wearethefoos** [comment]
@GuillaumeLegendre it looks like you are working from a project gemset with RVM, is that correct? See e.g. this path: `/Users/guillaumelegendre/.rvm/gems/ruby-2.3.0@investissement_pierre/gems`

It might be that it can't find the gem you installed globally because of this. Not sure though..

**Comment by wearethefoos** [comment]
Closing this now, feel free to reopen if it's still an issue though.
